In [1]:
import numpy as np, pandas as pd, plotly.express as px, plotly.graph_objects as go
from pathlib import Path

from SJ_Haar_CNV import base_search
from tests import test_data

In [2]:
X = np.array([0,0,0,1,1,1,2,2,2])
X

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [3]:
first_break = base_search.choose_break(X,0,X.size)
first_break

np.int64(2)

In [4]:
base_search.choose_break(X,first_break+1,X.size)

np.int64(3)

In [9]:
# I'm trying to manually figure out what's going on
l = X.size
s = first_break+1
e = l
matrix = base_search.haar_matrix(s,e,l)
scores = np.matmul(X,matrix)
best_options = np.argwhere(scores == scores.max()).flatten()
best_options[np.abs(best_options - l //2).argmin()]

np.int64(3)

In [10]:
scores

array([ 0.        ,  0.        ,  0.        ,  2.4754019 ,  1.63874187,
        0.87497926, -0.65254597, -2.32586603, -4.48611293])

In [ ]:
matrix

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.61237244, -0.20412415, -0.20412415,
        -0.20412415, -0.20412415, -0.20412415, -0.20412415],
       [ 0.        ,  0.        ,  0.45643546,  0.45643546, -0.27386128,
        -0.27386128, -0.27386128, -0.27386128, -0.27386128],
       [ 0.        ,  0.        ,  0.35355339,  0.35355339,  0.35355339,
        -0.35355339, -0.35355339, -0.35355339, -0.35355339],
       [ 0.        ,  0.        ,  0.27386128,  0.27386128,  0.27386128,
         0.27386128, -0.45643546, -0.45643546, -0.45643546],
       [ 0.        ,  0.        ,  0.20412415,  0.20412415,  0