In [1]:
import numpy as np, pandas as pd, plotly.express as px, plotly.graph_objects as go
from pathlib import Path

from SJ_Haar_CNV import base_search
from tests import test_data

In [2]:
X = np.concatenate([np.repeat (5,130), np.repeat (7,190), np.repeat(5,100)])
X

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,

In [3]:
first_break = base_search.choose_break(X,0,X.size)
first_break

130

In [4]:
test = base_search.create_basis_form(0, first_break, X.size)
test

[0, 0, 0, (0.07251407362812771, 130), (-0.032756357397533555, 290)]

In [5]:
second_break_one = base_search.choose_break(X,0,first_break)
second_break_one

26

In [6]:
second_break_two = base_search.choose_break(X,first_break+1,X.size)
second_break_two

320

In [7]:
# I'm trying to manually figure out what's going on
p0 = .95
s = 0
e = first_break
offset, matrix, scores, best_options, man_break, man_basis = base_search.choose_break(X,s, e, p0 = p0, debug = True)

In [8]:
offset

6

In [9]:
matrix[offset:matrix.shape[0]-offset].shape

(117, 130)

In [10]:
matrix.shape

(129, 130)

In [11]:
scores

array([1.71293908, 1.60839612, 1.51959215, 1.44287476, 1.37567934,
       1.31614484, 1.26288344, 1.21483619, 1.17117902, 1.13125971,
       1.09455434, 1.0606365 , 1.02915514, 0.99981823, 0.97238055,
       0.94663447, 0.92240283, 0.89953338, 0.87789451, 0.8573717 ,
       0.83786481, 0.81928583, 0.80155701, 0.7846094 , 0.76838161,
       0.75281875, 0.73787155, 0.72349569, 0.70965115, 0.69630165,
       0.68341425, 0.67095898, 0.65890842, 0.64723752, 0.63592327,
       0.62494452, 0.61428179, 0.6039171 , 0.59383379, 0.58401644,
       0.57445073, 0.56512334, 0.55602186, 0.5471347 , 0.53845105,
       0.52996077, 0.52165436, 0.51352289, 0.50555799, 0.49775174,
       0.49009671, 0.48258587, 0.47521255, 0.46797048, 0.46085368,
       0.45385648, 0.4469735 , 0.4401996 , 0.43352991, 0.42695976,
       0.42048468, 0.41410041, 0.40780285, 0.40158807, 0.39545231,
       0.38939191, 0.38340337, 0.3774833 , 0.37162841, 0.36583552,
       0.36010155, 0.35442348, 0.34879837, 0.34322337, 0.33769

In [12]:
best_options

array([7])

In [8]:
base_search.generate_haar_basis(X, p0=.95, length = 20, debug = True)

todo: 0, done: 0, len signal: 420
[(0, 130), (131, 420)]
todo: 1, done: 1, len signal: 130
[(131, 420), (0, 7), (8, 130)]
todo: 2, done: 2, len signal: 289
[(0, 7), (8, 130), (131, 320), (321, 420)]
[(8, 130), (131, 320), (321, 420)]
todo: 2, done: 3, len signal: 122
[(131, 320), (321, 420), (8, 15), (16, 130)]
todo: 3, done: 4, len signal: 189
[(321, 420), (8, 15), (16, 130), (131, 141), (142, 320)]
todo: 4, done: 5, len signal: 99
[(8, 15), (16, 130), (131, 141), (142, 320), (321, 326), (327, 420)]
[(16, 130), (131, 141), (142, 320), (321, 326), (327, 420)]
todo: 4, done: 6, len signal: 114
[(131, 141), (142, 320), (321, 326), (327, 420), (16, 22), (23, 130)]
[(142, 320), (321, 326), (327, 420), (16, 22), (23, 130)]
todo: 4, done: 7, len signal: 178
[(321, 326), (327, 420), (16, 22), (23, 130), (142, 151), (152, 320)]
[(327, 420), (16, 22), (23, 130), (142, 151), (152, 320)]
todo: 4, done: 8, len signal: 93
[(16, 22), (23, 130), (142, 151), (152, 320), (327, 332), (333, 420)]
[(23, 1

[[0, 0, 0, (0.07251407362812771, 130), (-0.032756357397533555, 290)],
 [0, 0, 0, (0.3425878167911703, 7), (-0.022282134425441996, 123)],
 [0, 0, 131, (0.042601432284230495, 320), (-0.08094272134003795, 100)],
 [0, 0, 8, (0.34186242656833027, 15), (-0.023781734022144698, 115)],
 [0, 0, 131, (0.29265326414436943, 141), (-0.017984278802167963, 179)],
 [0, 0, 321, (0.3958114029012639, 326), (-0.02526455763199556, 94)],
 [0, 0, 16, (0.36628061740041584, 22), (-0.023740410387063978, 108)],
 [0, 0, 142, (0.3072676485105926, 151), (-0.018181517663348662, 169)],
 [0, 0, 327, (0.39500426427359775, 332), (-0.02693210892774531, 88)],
 [0, 0, 23, (0.365510442529189, 29), (-0.02533240690796361, 101)],
 [0, 0, 152, (0.30672926211349055, 161), (-0.019291148560596903, 159)],
 [0, 0, 333, (0.39408505465575616, 338), (-0.02883549180407972, 82)],
 [0, 0, 30, (0.3959364552142891, 35), (-0.025006512960902463, 95)],
 [0, 0, 162, (0.32376195411908804, 170), (-0.019425717247145285, 150)],
 [0, 0, 339, (0.39302